# Generated by Django 3.1.2 on 2020-10-23 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=50, unique=True)),
                ('created_course', models.DateTimeField(auto_now_add=True)),
                ('modified_course', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut_teacher', models.CharField(max_length=12, unique=True)),
                ('first_name_teacher', models.CharField(max_length=75)),
                ('last_name_teacher', models.CharField(max_length=75)),
                ('address_teacher', models.CharField(max_length=100)),
                ('phone_number_teacher', models.IntegerField(blank=True, max_length=9, null=True)),
                ('email_teacher', models.EmailField(max_length=150)),
                ('status_teacher', models.BooleanField(default=True)),
                ('created_teacher', models.DateTimeField(auto_now_add=True)),
                ('modified_teacher', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recordatorio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75, null=True)),
                ('description', models.TextField(blank=True, max_length=200, null=True)),
                ('start_date', models.DateField(auto_now=True)),
                ('end_date', models.DateField(auto_now=True)),
                ('alarm', models.BooleanField(default=True)),
                ('created_reminder', models.DateTimeField(auto_now_add=True)),
                ('modified_reminder', models.DateTimeField(auto_now=True)),
                ('teacher_rec_fk', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Profesores.profesor')),
            ],
        ),
        migrations.CreateModel(
            name='CursoProfesor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_course_teacher', models.DateTimeField(auto_now_add=True)),
                ('modified_course_teacher', models.DateTimeField(auto_now=True)),
                ('Course_fk', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Profesores.curso')),
                ('teacher_fk', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Profesores.profesor')),
            ],
        ),
    ]
